"""vacation

Revision ID: b6841ef868b2
Revises: 27bf2aa3b8c7
Create Date: 2024-11-10 21:49:23.393833

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b6841ef868b2"
down_revision = "27bf2aa3b8c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vacation",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "vacation_type",
            postgresql.ENUM("UnpaidLeave", "PaidLeave", name="vacationtype"),
            nullable=False,
        ),
        sa.Column("start_date", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("end_date", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["employee.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vacation_end_date"), "vacation", ["end_date"], unique=False
    )
    op.create_index(op.f("ix_vacation_id"), "vacation", ["id"], unique=False)
    op.create_index(
        op.f("ix_vacation_start_date"), "vacation", ["start_date"], unique=False
    )
    op.create_index(op.f("ix_vacation_user_id"), "vacation", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_vacation_vacation_type"), "vacation", ["vacation_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vacation_vacation_type"), table_name="vacation")
    op.drop_index(op.f("ix_vacation_user_id"), table_name="vacation")
    op.drop_index(op.f("ix_vacation_start_date"), table_name="vacation")
    op.drop_index(op.f("ix_vacation_id"), table_name="vacation")
    op.drop_index(op.f("ix_vacation_end_date"), table_name="vacation")
    op.drop_table("vacation")
    # ### end Alembic commands ###
    # TODO remove "vacationtype" from DB
